name: Format and Lint
on:
  push:
  pull_request:
    branches: [main]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.repository != github.event.pull_request.head.repo.full_name)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [23]
    steps:
      - name: Check out branch (pull request)
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install packages
        run: npm ci
      - name: Check Formatting with Prettier
        run: npx prettier --check .
      - name: Lint with ESLint
        run: npx eslint .
